<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script>
       //function 안만들고 함수로!!
        // const delayAdd = (index, cb, errorCb) => { // 1: 인자  2: 1을 이어받아 정상적으로 처리 3: 앞에 것들 문제가 발생했을 때
        //     setTimeout(()=>{
        //         if(index > 10){
        //             errorCb(`${index}는 10보다 클 수 없다.`);
        //             return;
        //                             //그냥 retrn만으로 종료할 수 있음.
        //         }
        //         console.log(index);
        //         cb(index + 1);
        //     }, 1000);
        // }

    // delayAdd(4, 
    //     (res)=>{console.log(res)},    //출력 : 4   5
    //     (err)=>{console.error(err)});   //  System.err 같은 느낌?? 이게 있으면 더 풍부하게 사용 가능!!



//     const delayAdd = (index) => { // 정상적으로 동작할 함수
//         return new Promise((resolve, reject) => { // 프라미스라는 클래스가 오버로딩 되어있음!! 생성자가 만들어져 있음!! 이 변수명이 관례!!
//             setTimeout(()=>{
//             if(index > 10){
//                 reject(`${index}는 10보다 클 수 없다.`);
//                 return;
//                                 //그냥 retrn만으로 종료할 수 있음.
//             }
//             console.log(index);
//             resolve(index + 1);
//         }, 1000);
//     });
// }    


//     delayAdd(4)
//         .then((res)=>{console.log(res)})
//         .catch((err)=>{console.log(err)}) // 에러는 catch

    // const wrap = async () => {
    //    const res = await delayAdd(11); //에러는 catch 그런데 순서가 아니라 오류가 나면 이걸 출력하므로 분기임!!  catch를 못쓰고 try catch 사용해야 함.
    //    console.log(res);

    // }
    // wrap();

    // const wrap = async () => {
    //     try{
    //         const res = await delayAdd(11); //에러는 catch 그런데 순서가 아니라 오류가 나면 이걸 출력하므로 분기임!!  catch를 못쓰고 try catch 사용해야 함.
    //         console.log(res);
    //     }
    //     catch(err){
    //         console.error(err);
    //     }
    //     finally{
    //         console.log("Done!");
    //     }
    // }
    // wrap();


    const getMovies = (movieName) => {
        return new Promise((resolve, reject)=>{
            fetch(`https://www.omdbapi.com/?apikey=7035c60c&s=${movieName}`) // 쌍 따옴표안에 같이 쓰려면 ""이게 아니라 ``이거 써야함!!
            .then(res => res.json()) 
            .then((json)=>{
                console.log(json, `${movieName}`); // 밖에서 뿌릴꺼면 이걸 지워주기!!
                if(json.Response === `False`){
                    reject(json.Error);
                }
                resolve(`${movieName}`, json); // 영화목록 나오는 것!! 근데 위에서 출력하고 있어서 굳이 필요가 없음!
                })
                .catch((error)=>{
                    reject(error); // try를 포함한 상황! // 주소가 틀렸을 때 여기가 잡음!!
                });
            });
        };
        
        //async await
        const movie = async ()=> {
            try{
                movies = await getMovies('avengers');
                console.log('영화 이름 및 목록 : ', movies);
                movies = await getMovies('avatar');
                console.log('영화 이름 및 목록 : ', movies);
            }
            catch(err){
                console.log('에러발생 : ', err);
            }
        }
        movie();

        //
        //     const wrap = async () => {
        //             getMovies('frozen')
        //             .then((movies)=>{console.log('영화목록 : ', movies)})// 안쓰면 빼줘두 되긴 함!!
        //             .catch((error)=>{console.log('에러 발생: ', error)})            
        //             .finally(()=>{console.log("끝!")});
        //     }
        //         wrap();
        </script>
</head>
<body>
</body>
</html>